version: '3.1'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    env_file:
      - env/.pg.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - postgresql
    build: .
    restart: on-failure
    env_file:
      - env/.spring-pg.env
    ports:
      - "6969:6969"

volumes:
  db:
