version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: postgresql

    env_file:
      - env/.pg.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres

volumes:
  db:
